<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="container">
<h3><?php /* @escapeNotVerified */ echo __('Write Us') ?></h3><br />
<p><?php /* @escapeNotVerified */ echo __('Jot us a note and we’ll get back to you as quickly as possible.') ?></p>

<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      style="float:left;width:100%;" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    
    <div class="input-group input-group-lg field name required"><span class="input-group-addon"><span class="icon icon-user"></span></span>
        <input placeholder="Enter your name" name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="form-control" type="text" data-validate="{required:true}"/>
    </div>

       <div class="input-group field email required input-group-lg"><span class="input-group-addon"><span class="icon icon-envelope"></span></span>

        <input name="email"  placeholder="Enter your email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="form-control" type="email" data-validate="{required:true, 'validate-email':true}"/>
    </div>

           <div class="input-group field telephone required input-group-lg"><span class="input-group-addon"><span class="icon icon-phone"></span></span>

        <input name="telephone" placeholder="Enter your telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="form-control" type="text" />
    </div>

    <div class="input-group input-group-lg field comment required">
        <textarea placeholder="Your Message Here" name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="form-control" cols="5" rows="3" data-validate="{required:true}"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
    </div>

    <?php echo $block->getChildHtml('form.additional.info'); ?>

    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button style="margin-top: 50px;" type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="btn btn-custom">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>

</div>

<?php echo $this->getLayout()
          ->createBlock('Magento\Cms\Block\Block')
          ->setBlockId('home-contact-block')
          ->toHtml();
		  ?>