<!--<button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
        data-target="#<?php //echo $this->getToggleId() ?>"
        aria-expanded="false">
    <span class="sr-only"><?php /* @escapeNotVerified */ //echo __('MENU') ?></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</button>
-->
 <?php 
    echo $block->getLayout()
               ->createBlock('Magento\Cms\Block\Block')
               ->setBlockId('menu-block')
               ->toHtml();
			   ?>